@startuml ClassDiagram
skinparam Linetype ortho

class Restaurant{
    - member : list of Member
    - order_list : list of Order
    - stock : list of Item
    - coupon_list : list of Coupon
    - receipt_log : list of Receipt
    - room : list of Room
    - staff : list of Staff
    - menu : list of MenuItem
    - payment_gateway : PaymentMethod
    - booking_list : list of Booking
    + add_coupon(Coupon)
    + get_coupon_by_code(code)
    + booking_room(staff_id, member_id, room_id, amount_paid, start_time, hours)
    + add_booking(booking: Booking)
    + is_slot_available(room, start, hours)
    + auto_check_no_show()
    + get_bookings_by_status(status): List[Booking]
    + get_booking_by_id(booking_id)
    + give_coupon(Customer, Coupon)
    + find_item_in_reserved(Item)
    + create_delivery_order()
    + process_order_payment(order_id, staff_id, coupon, method, details) : Dict
    + preview_order_bill(order_id, staff_id, coupon) : Dict
    + check_and_issue_reward(order: Order) : str
}
Customer --|> User
Staff --|> User
class User{
    - id : string
    - name : string
    - phoneNumber : string
    + get_id()
    + get_name()
}
Restaurant o-- Member
Member--|>Customer
Guest--|>Customer
class Customer {
    <<Abstract>>
    + request_bill()
}
class Guest {
    + register()
}
class Member{
    - coupon_list : list[Coupon]
    - receipt_list : list[Recipt]
    - tier : MemberTier
    + add_receipt(receipt)
    + add_coupon(Coupon)
    + get_tier()
}

Restaurant o-- Staff
class Staff{
    - username
    - password
    - role : StaffRole
    + login()
    + logout()
    + create_order()
    + check_room_availability(room, start, hours)
    + check_in_booking(booking_id)
    + check_out_booking(booking_id)
    + view_queue()
    + update_food_status()
    + report_waste() 
    + void_bill()  
}

Restaurant o-- Order
Restaurant o-- MenuItem
Order *-- OrderItem
Order --> Booking
Order --> Customer
OrderItem --> MenuItem
Ingredient --> Item
Item --o Restaurant
SingleMenuItem --|> MenuItem
SingleMenuItem o-- Ingredient
SetMenuItem --|> MenuItem
SingleMenuItem <-- Food
Food --o SetMenuItem

class Order{
    - id:  string
    - type : DineIn, Event, Delivery
    - customer : Customer
    - order_list : list of OrderItem
    - sub_total_price : float
    - status_start : datetime
    - discount : float
    - final_price : float
    - booking : Booking
    - delivery : Delivery
    - status : none, reserved, confirmed, paided, cooking, ready, served, cancelled
    + update_status(OrderStatus)
    + pre_calculate_totals(coupon: Coupon)
    + calculate_totals(coupon: Coupon)
    + execute_payment(method: PaymentMethod, details: Dict, coupon: str) : Receipt
    + booking() : Booking
    + pre_calculate_totals(coupon: Coupon)
}
class OrderItem{
    - menu_item : MenuItem
    - quantity : int
    - status : OrderItemStatus
    + update_status(OrderItemStatus)
    + get_details() : Dict<str, Any>
}

abstract class MenuItem{
    - name : str
    - price : float
    - cooking_time : datetime
    - menu_item_status : available, out_of_stock, deleted
    + update_status(MenuItemStatus)
    + get_all_ingredient()
    + update_price()
}
class SingleMenuItem{
    - recipe : list of Ingredient
    - customization : list of Ingredient [that can modify]
    - cooking_time : datetime
    + custom(Item, quantity: int)
}
class SetMenuItem{
    - items : list of Food
    + get_all_ingredient()
}
class Food{
    - item : SingleMenuItem
    - quantity : int
}
class Ingredient{
    - item : Item
    - quantity : int
}
class Item{
    - name : string
    - unit_cost : float
}



FixedAmountCoupon --|> Coupon
PercentCoupon --|> Coupon
Coupon --o Member

class Room{
    - room_id : str
    - name : str
    - status : RoomStatus
    - capacity : int
    - price_per_hour : float
    + update_status(RoomStatus)
}
Restaurant o-- Room
Restaurant o-- Booking
Booking --> Member
Booking --> Room
Booking *-- TimeSlot
class Booking{
    - booking_id : str
    - member : Member
    - room : Room
    - time_slot : TimeSlot
    - status : BookingStatus
    - total_price : float
    - deposit_price : float
    + add_order(Order)
    + add_time_slot(room, start_time, hours)
    + get_details() : Dict<str, Any>
}
class TimeSlot{
    - start_time : datetime
    - end_time : datetime
    - hours : int
}
abstract class Coupon{
    - id : str
    - code : str
    - minimum_price : float
    - status : CouponStatus
    + {abstract} apply_coupon(base_price: float) : float
    + is_applicable(base_price: float) : bool
    + mark_as_used()
}
class PercentCoupon{
    - percent : int
    + apply_coupon(base_price: float)
}
class FixedAmountCoupon{
    - amount : float
    + apply_coupon(base_price: float)
}

Delivery <-- Order
class Delivery{
    delivery_id : str
    - platform : DeliveryPlatform
    - commission_rate : float
    - distance : float
    - status : DeliveryStatus
    - delivery_status : finding_driver, driver_assigned, driver_at _store, out_for_delivery, delivered
    + update_status(DeliveryStatus)
    + fee() : float
}
PaymentMethod <-- Restaurant
abstract class PaymentMethod{
    - id : str
    - name : str
    + get_method(name:str)
    + get_name() : abstract
    + {abstract} pay(amount: float, kwargs) : Tuple<bool, str>
}

QRCode --|> PaymentMethod
class QRCode{

}

Cash --|> PaymentMethod
class Cash{
    
}

CreditCard --|> PaymentMethod
class CreditCard{
    
}

Restaurant o-- Receipt
Member o-- Receipt
PaymentMethod <-- Receipt
Customer <-- Receipt
Order <-- Receipt
class Receipt{
    - id : str
    - order : Order
    - time : datetime
    - payment_method : PaymentMethod
}



package "Enums" {
    enum OrderType {
        GENERAL
        DELIVERY
        EVENT
    }
    enum OrderStatus {
        PENDING
        PAID
        CANCELED
    }
    enum BookingStatus {
        PENDING
        DEPOSIT_PAID
        CHECKED_IN
        COMPLETED
        CANCELLED
    }
    enum RoomStatus {
        AVAILABLE
        IN_USE
        CLEANING
    }
    enum RoomType {
        VIP
        STANDARD
        HALL
    }
    enum MemberTier {
        BRONZE
        SILVER
        GOLD
    }
    enum CouponStatus {
        AVAILABLE
        NOT_AVAILABLE
    }
    enum StaffRole {
        PartyStaff
        KitchenStaff
    }
    enum TransactionStatus {
        PENDING
        FAILED
        SUCCESS
    }
}

@enduml
