@startuml ClassDiagram

class Restaurant{
    - member : list of Member
    - queue : list of Order <in comfirm, paided, and cooking state>
    - coupon_list : list of Coupon
    - transaction_log : list of Transaction
    - room : list of Room
    - staff : list of Staff
    + add_coupon(Coupon)
    + get_coupon_by_code(code)
    - create_transaction()
    - booking_room(staff_id, member_id, room_id, amount_paid, start_time, hours)
}
Customer --|> User
Staff --|> User
class User{
    -id : string
    -name : string
    -phoneNumber : string
    + get_id()
}
Restaurant o-- Member
Member--|>Customer
Guest--|>Customer
class Customer {
    <<Abstract>>
}
class Guest {

}
class Member{
    - coupon_code_list : list
    - tier : str= Silver, Gold
    + add_coupon(code)
    + validate_coupon(code)
    + mark_coupon_as_used(code)
}

Restaurant o-- Staff
FrontStaff--|>Staff
PartyStaff--|>Staff
KitchenStaff--|>Staff
Manager--|>Staff
Manager--|>FrontStaff
Manager--|>PartyStaff
Manager--|>KitchenStaff
class Staff{
    <<Abstract>>
}
class FrontStaff{
    
}
class PartyStaff{
    - role : str = "Party Staff"
}
class KitchenStaff{
    
}
class Manager{

}

DineInOrder --|> Order
EventOrder --|> Order
DeliveryOrder --|> Order

class DineInOrder{
    
}
class EventOrder{
    - id : str
    - total_price : float
    - status : str
}
class DeliveryOrder{
    
}

Restaurant o-- Order
Order *-- Food
Food --> Particular
Particular o-- Ingredient
Ingredient --> Item

class Order{
    -id:  string
    -type : DineIn, Party, Delivery
    -customer_id : string
    -food : list Food
    -total_price : float
    -time : datetime
    -status : none, confirmed, paided, cooking, finish, cancle
}
class Food{
    -particular : Particular
    -quantity : int
    -status : none, available, out_of_stock, cooking, finish, cancle
}
class Particular{
    -list recipe : Ingredient
    -price : float
}
Burger --|> Particular
ChickenSet --|> Particular
class Burger{
    + custom()
}
class ChickenSet{
    
}
class Ingredient{
    -item : Item
    -quantity : int
}
class Item{
    -name : string
}

Restaurant --> Menu
Menu o-- MenuFood
MenuFood --> Particular
class Menu{
    - food : list MenuFood
}
class MenuFood{
    - particular : Particular
    - status : available, out_of_stock, deleted
}

Restaurant --> Stock
class Stock{
    - reserved : list StockIngredient
    - real_stock : list StockIngredient
}

Stock o-- StockIngredient
StockIngredient --> Item
class StockIngredient{
    - item : Item
    - quantity : int
}

BookingManager o-- Booking
Booking --> Coupon
PercentCoupon --|> Coupon
EventOrder --* Booking

Coupon --o Restaurant
class room{
    - room_id : str
    - name : str
    - status : str = "Available", "Reserved", "In_Use", "Cleaning"
    - capacity : int
    - price_per_hour : float
}
Restaurant o-- room
class BookingManager{
    - booking_list : list of Booking
    + add_booking(booking)
    + get_member_form_id(booking_id)
    + get_event_order_from_id(booking_id)
    + get_booking_from_id(booking_id)
    + auto_check_no_show()
    + is_slot_available(room_id, start_time, end_time)
}
class Booking{
    - booking_id : str
    - member : Member
    - room : Room
    - start_time : datetime
    - end_time : datetime
    - hours : int
    - status : str
    - event_order : EventOrder
    - coupon : Coupon
    - discount_price : float
    - total_price : float
    - deposit_price : float
    - deposit_status : str
    + add_event_order(EventOrder)
}
class Coupon{
    <<Abstract>>
    - id : str
    - code : str
    - minimum_price : float
    + apply_coupon(base_price)
}
class PercentCoupon{
    - percent : int
}
DeriveryPlatform <-- Restaurant
class DeriveryPlatform{

}
PaymentGateway <-- Restaurant
class PaymentGateway{

}

Restaurant o-- Transaction
class Transaction{
    - type : DineIn, Event, Delivery
    - customer_id : str
    - amount : float
    - time : datetime
    - tx_id : str
}

class Log{
    - log : list of LogEntry
    + add_log(entry)
    + get_all_log()
}

class SimulationClock{
    - current_time : datetime
    + get_time()
    + set__time(new_time)
}

@enduml
